---
- name: Install K3s agent
  shell: |
    curl -sfL https://get.k3s.io | sh -s - agent \
      --server https://{{ k3s_master_ip }}:6443 \
      --token {{ k3s_token }}
  args:
    creates: /usr/local/bin/k3s
  when: k3s_token is defined and k3s_master_ip is defined

- name: Wait for K3s agent to be ready
  wait_for:
    port: 10250
    host: "{{ ansible_default_ipv4.address }}"
    delay: 10
    timeout: 300
  when: k3s_token is defined and k3s_master_ip is defined
