version: "3.9"
services:
  alertmanager:
    image: prom/alertmanager:v0.27.0
    ports: [ "9093:9093" ]
    volumes:
      - ./alertmanager/config.yml:/etc/alertmanager/config.yml:ro
    command: --config.file=/etc/alertmanager/config.yml

  grafana:
    image: grafana/grafana:10.4.2
    ports: [ "3000:3000" ]
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on: [ victoriametrics ]

  victoriametrics:
    image: victoriametrics/victoria-metrics:v1.103.0
    command: -retentionPeriod=1
    ports: [ "8428:8428" ]
    volumes: [ "vm-data:/victoria-metrics-data" ]

  vmalert:
    image: victoriametrics/vmalert:v1.103.0
    command:
      - -datasource.url=http://victoriametrics:8428
      - -rule=/etc/vmalert/rules.yml
      - -notifier.url=http://alertmanager:9093
    volumes:
      - ./vmalert/rules.yml:/etc/vmalert/rules.yml
    depends_on: [ victoriametrics ]

  vmagent:
    image: victoriametrics/vmagent:v1.103.0
    command:
      - -promscrape.config=/etc/vmagent/prometheus.yml
      - -remoteWrite.url=http://victoriametrics:8428/api/v1/write
    volumes:
      - ./vmagent/prometheus.yml:/etc/vmagent/prometheus.yml
    depends_on: [ victoriametrics ]

  loki:
    image: grafana/loki:2.9.4
    ports: [ "3100:3100" ]
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:2.9.4
    volumes:
      - /var/log:/var/log:ro
      - ./promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    depends_on: [ loki ]

volumes:
  grafana-data:
  vm-data:
