apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: telemetry
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://github.com/OWNER/REPO.git
  ref:
    branch: main

