apiVersion: v1
kind: Secret
metadata:
  name: telemetry-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  postgres-password: {{ ( .Values.postgres.password | default (randAlphaNum 16) ) | b64enc }}
  rabbitmq-password: {{ ( .Values.rabbitmq.password | default (randAlphaNum 16) ) | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  postgres-password: {{ ( .Values.postgres.password | default (randAlphaNum 16) ) | b64enc }}
  postgres-user: {{ .Values.postgres.user | b64enc }}
  postgres-db: {{ .Values.postgres.database | b64enc }}
